
version: '2'

services:

  demo-smallinvoice-api-h2:
    image: uportal/demo-smallinvoice-api:latest
    container_name: demo-smallinvoice-api-h2
    restart: always
    environment:
      APP_NAME: Small Invoice Demo App with H2
      ACTIVE_PROFILES: dev,h2,smallinvoice
      APP_URL: http://localhost:8080
      SMALLINVOICE_URL: https://demo-api.smallinvoice.com
      SMALLINVOICE_CLIENT_ID: XNG74DQ3DAA2ZUV4TLWU
      SMALLINVOICE_CLIENT_SECRET: uhSBgyRASXmaNvemv3QXBEIjZsGY5574balf73lNa0PlSrNDsl02MUDYC6/YN6NbtKjE0kxvedtT+RHI
      SMALLINVOICE_SCOPE: profile contact letter catalog invoice offer delivery_note order_confirmation project cost_unit working_hours activity effort contact_reminder configuration}

    ports:
      - 8080:8080
